AI Externship Assignment 2
Name: Madhu Vanthi Sankar Ganesh
Reg No : 20BRS1113
Campus : VIT CHENNAI

In [ ]:
#Build an ANN model for drug classification

In [ ]:

# importing the required lib

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


In [ ]:
!unzip "/content/archive (2).zip" -d "/content/"

Archive:  /content/archive (2).zip
  inflating: /content/drug200.csv    


In [ ]:

# Reading the csv file

df = pd.read_csv('/content/drug200.csv')

# Visualizing the 1st 5 observations

df.head()

Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  DrugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  DrugY

In [ ]:
# descriptive stat
df.describe(include='all')


Age  Sex    BP Cholesterol     Na_to_K   Drug
count   200.000000  200   200         200  200.000000    200
unique         NaN    2     3           2         NaN      5
top            NaN    M  HIGH        HIGH         NaN  DrugY
freq           NaN  104    77         103         NaN     91
mean     44.315000  NaN   NaN         NaN   16.084485    NaN
std      16.544315  NaN   NaN         NaN    7.223956    NaN
min      15.000000  NaN   NaN         NaN    6.269000    NaN
25%      31.000000  NaN   NaN         NaN   10.445500    NaN
50%      45.000000  NaN   NaN         NaN   13.936500    NaN
75%      58.000000  NaN   NaN         NaN   19.380000    NaN
max      74.000000  NaN   NaN         NaN   38.247000    NaN

In [ ]:

# Check the null values

df.isnull().sum()

Age            0
Sex            0
BP             0
Cholesterol    0
Na_to_K        0
Drug           0
dtype: int64

In [ ]:
x = df.iloc[:,0:5] # iloc[:,:]
x.head(2)

Age Sex    BP Cholesterol  Na_to_K
0   23   F  HIGH        HIGH   25.355
1   47   M   LOW        HIGH   13.093

In [ ]:
print(df.Drug.unique())

['DrugY' 'drugC' 'drugX' 'drugA' 'drugB']


In [ ]:

y = df['Drug']
y[0:2]


0    DrugY
1    drugC
Name: Drug, dtype: object

In [ ]:

from sklearn.model_selection import train_test_split



In [ ]:

xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.2,random_state=12)

In [ ]:
from sklearn.preprocessing import LabelEncoder


In [ ]:

le = LabelEncoder() # initialize the lib

In [ ]:
ytest

23     DrugY
182    drugX
172    DrugY
21     DrugY
63     drugX
11     DrugY
61     drugA
32     drugX
164    DrugY
7      drugC
95     drugX
173    DrugY
132    drugX
120    DrugY
98     DrugY
138    drugB
31     drugB
16     drugX
181    drugX
85     drugB
185    DrugY
166    DrugY
101    drugA
129    drugX
113    drugX
51     drugX
167    drugX
88     DrugY
108    drugB
136    drugB
29     DrugY
183    DrugY
152    drugX
93     DrugY
189    DrugY
139    drugX
179    DrugY
55     drugC
1      drugC
5      drugX
Name: Drug, dtype: object

In [ ]:

xtrain['Sex'] = le.fit_transform(xtrain['Sex'])
xtrain['Sex']


77     0
47     1
94     1
14     0
41     0
      ..
3      0
130    0
134    0
155    1
75     1
Name: Sex, Length: 160, dtype: int64

In [ ]:
xtrain['BP'] = le.fit_transform(xtrain['BP'])
xtrain['BP']

77     0
47     1
94     1
14     2
41     0
      ..
3      2
130    2
134    0
155    1
75     1
Name: BP, Length: 160, dtype: int64

In [ ]:
xtrain['Cholesterol'] = le.fit_transform(xtrain['Cholesterol'])
xtrain['Cholesterol']

77     1
47     0
94     0
14     0
41     1
      ..
3      0
130    0
134    0
155    0
75     1
Name: Cholesterol, Length: 160, dtype: int64

In [ ]:
xtest['Sex'] = le.fit_transform(xtest['Sex'])
xtest['Sex']
xtest['BP'] = le.fit_transform(xtest['BP'])
xtest['BP']
xtest['Cholesterol'] = le.fit_transform(xtest['Cholesterol'])
xtest['Cholesterol']

23     0
182    1
172    1
21     0
63     1
11     1
61     1
32     1
164    1
7      0
95     1
173    1
132    1
120    0
98     1
138    1
31     0
16     1
181    0
85     0
185    1
166    0
101    0
129    0
113    1
51     1
167    0
88     1
108    1
136    0
29     0
183    1
152    1
93     1
189    1
139    0
179    0
55     0
1      0
5      0
Name: Cholesterol, dtype: int64

In [ ]:
ytrain

array([0, 3, 0, 4, 2, 0, 0, 0, 4, 0, 0, 0, 0, 4, 4, 2, 0, 3, 0, 3, 0, 0,
       4, 2, 4, 4, 0, 0, 1, 0, 4, 1, 0, 4, 4, 4, 2, 1, 0, 4, 4, 4, 0, 0,
       4, 1, 4, 1, 0, 1, 0, 0, 4, 1, 0, 3, 1, 1, 1, 4, 1, 0, 0, 4, 0, 1,
       0, 2, 3, 0, 3, 1, 0, 4, 0, 0, 0, 0, 4, 0, 4, 3, 0, 2, 0, 0, 1, 4,
       2, 4, 0, 4, 0, 0, 0, 4, 2, 4, 1, 3, 0, 4, 4, 0, 0, 0, 3, 0, 4, 3,
       0, 2, 0, 0, 0, 0, 0, 4, 0, 0, 2, 0, 4, 4, 1, 4, 1, 0, 0, 0, 4, 4,
       0, 0, 3, 2, 0, 1, 4, 0, 3, 0, 0, 4, 0, 0, 1, 4, 0, 0, 0, 0, 0, 1,
       1, 4, 0, 0, 3, 0])

In [ ]:
ytrain = le.fit_transform(ytrain)
ytrain

array([0, 3, 0, 4, 2, 0, 0, 0, 4, 0, 0, 0, 0, 4, 4, 2, 0, 3, 0, 3, 0, 0,
       4, 2, 4, 4, 0, 0, 1, 0, 4, 1, 0, 4, 4, 4, 2, 1, 0, 4, 4, 4, 0, 0,
       4, 1, 4, 1, 0, 1, 0, 0, 4, 1, 0, 3, 1, 1, 1, 4, 1, 0, 0, 4, 0, 1,
       0, 2, 3, 0, 3, 1, 0, 4, 0, 0, 0, 0, 4, 0, 4, 3, 0, 2, 0, 0, 1, 4,
       2, 4, 0, 4, 0, 0, 0, 4, 2, 4, 1, 3, 0, 4, 4, 0, 0, 0, 3, 0, 4, 3,
       0, 2, 0, 0, 0, 0, 0, 4, 0, 0, 2, 0, 4, 4, 1, 4, 1, 0, 0, 0, 4, 4,
       0, 0, 3, 2, 0, 1, 4, 0, 3, 0, 0, 4, 0, 0, 1, 4, 0, 0, 0, 0, 0, 1,
       1, 4, 0, 0, 3, 0])

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense


In [ ]:
input_dim = xtrain.shape[1]
output_classes = len(np.unique(y))
input_dim

5

In [ ]:
xtrain.shape, xtest.shape, ytrain.shape, ytest.shape

((160, 5), (40, 5), (160,), (40,))

In [ ]:
input_dim = xtrain.shape[1]
output_classes = len(np.unique(y))
# Initializing the seq model
reg_model = Sequential()
# Adding the input layer to the model
reg_model.add(Dense(64, activation='relu',input_dim=input_dim))
# Adding the 1st hidden layer to the model
reg_model.add(Dense(128,activation='relu'))
# Adding the 2nd hidden layer to the model
reg_model.add(Dense(64,activation='relu'))
# Adding output layer
reg_model.add(Dense(output_classes,activation='softmax'))


In [ ]:
reg_model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:

# Training the model

reg_model.fit(xtrain,ytrain,batch_size=5,epochs=35)

Epoch 1/35
32/32 [==============================] - 1s 2ms/step - loss: 1.5713 - accuracy: 0.4812
Epoch 2/35
32/32 [==============================] - 0s 2ms/step - loss: 1.1807 - accuracy: 0.5188
Epoch 3/35
32/32 [==============================] - 0s 2ms/step - loss: 1.0297 - accuracy: 0.6125
Epoch 4/35
32/32 [==============================] - 0s 3ms/step - loss: 1.0931 - accuracy: 0.5688
Epoch 5/35
32/32 [==============================] - 0s 2ms/step - loss: 0.9299 - accuracy: 0.6187
Epoch 6/35
32/32 [==============================] - 0s 1ms/step - loss: 0.9492 - accuracy: 0.6375
Epoch 7/35
32/32 [==============================] - 0s 2ms/step - loss: 0.8314 - accuracy: 0.6687
Epoch 8/35
32/32 [==============================] - 0s 2ms/step - loss: 0.7957 - accuracy: 0.6625
Epoch 9/35
32/32 [==============================] - 0s 2ms/step - loss: 0.8508 - accuracy: 0.6562
Epoch 10/35
32/32 [==============================] - 0s 1ms/step - loss: 0.8783 - accuracy: 0.6812
Epoch 11/35
32/32 [

In [ ]:
xtest

Age  Sex  BP  Cholesterol  Na_to_K
23    48    0   1            0   15.036
182   20    0   1            1   11.686
172   39    0   2            1   17.225
21    63    1   2            0   25.917
63    45    1   1            1    8.370
11    34    0   0            1   19.199
61    24    1   0            1    9.475
32    49    1   1            1   11.014
164   16    1   0            1   19.007
7     41    1   1            0   11.037
95    36    1   1            1   11.424
173   41    0   1            1   18.739
132   49    1   1            1   13.598
120   28    1   2            0   27.064
98    20    1   0            1   35.639
138   51    1   0            1   11.343
31    74    1   0            0    9.567
16    69    1   1            1   11.455
181   59    0   2            0   13.884
85    59    1   0            0   13.935
185   57    0   2            1   25.893
166   58    0   1            0   26.645
101   45    0   0            0   12.854
129   32    0   2            0    7.477
113   65    0   1            1   13.769
51    67    1   2            1   10.898
167   57    0   2            0   14.216
88    37    0   0            1   23.091
108   72    1   0            1    9.677
136   55    0   0            0   10.977
29    45    1   1            0   17.951
183   36    0   0            1   15.490
152   55    1   2            1    7.261
93    42    0   1            1   29.271
189   64    1   0            1   20.932
139   69    0   2            0   10.065
179   67    0   2            0   15.891
55    26    0   1            0   14.160
1     47    1   1            0   13.093
5     22    0   2            0    8.607

In [ ]:
ypred = reg_model.predict(xtest)

2/2 [==============================] - 0s 4ms/step


In [ ]:
ypred[1]

array([0.2873866 , 0.03233948, 0.00111317, 0.10175985, 0.57740086],
      dtype=float32)

In [ ]:
ypred = np.argmax(ypred)

In [ ]:
ytest = le.fit_transform(ytest)
ytest

array([0, 4, 0, 0, 4, 0, 1, 4, 0, 3, 4, 0, 4, 0, 0, 2, 2, 4, 4, 2, 0, 0,
       1, 4, 4, 4, 4, 0, 2, 2, 0, 0, 4, 0, 0, 4, 0, 3, 3, 4])

In [ ]:
output = ['DrugY' 'drugC' 'drugX' 'drugA' 'drugB']
output[ypred[1]]

IndexError: ignored

In [ ]:
loss, accuracy = reg_model.evaluate(xtest, ytest, verbose=0)
print('Test Loss:', loss)
print('Test Accuracy:', accuracy)

Test Loss: 0.520915687084198
Test Accuracy: 0.75


In [ ]:
ypred = reg_model.predict([[28,0,2,0,7.798]])

1/1 [==============================] - 0s 42ms/step


In [ ]:
ypred

array([[1.9559078e-02, 5.6682789e-04, 1.2306773e-04, 2.8178465e-02,
        9.5157260e-01]], dtype=float32)

In [ ]:
ypred = np.argmax(ypred)

In [ ]:
ypred

4

In [ ]:
output = ['DrugY', 'drugC' ,'drugX', 'drugA' ,'drugB']
output[ypred]

'drugB'